"""V10 S3 Writer — Uploads V10 research data to dedicated bucket.

Bucket: v10-engine (eu-west-2)
Structure: v10/{dataset}/symbol={PAIR}/date={YYYY-MM-DD}/{dataset}.jsonl

Only real trading symbols. No test/mock data.
Schema validated before upload. Never raises.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any

from core.v10.schema_contract import SCHEMA_VERSION, validate_decision_record

logger = logging.getLogger(__name__)

# ═══════════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════════

BUCKET_NAME = "v10-engine"
BUCKET_REGION = "eu-west-2"

# Only real trading symbols may be written
ALLOWED_SYMBOLS = frozenset({
    "EURUSD", "GBPUSD", "USDJPY", "USDCHF", "USDCAD", "AUDUSD", "NZDUSD",
    "NAS100", "US500", "XAUUSD",
    # Broker-suffixed variants
    "EURUSD_SB", "GBPUSD_SB", "USDJPY_SB", "USDCHF_SB", "USDCAD_SB",
    "AUDUSD_SB", "NZDUSD_SB", "NAS100_SB", "US500_SB", "XAUUSD_SB",
})

# Forbidden prefixes (test/mock/debug)
FORBIDDEN_PREFIXES = ("TEST", "MOCK", "FAKE", "DUMMY", "FIXTURE", "DEBUG")

# Minimum observation_id length (production IDs are 16-char hex from sha256)
_MIN_OBSERVATION_ID_LENGTH = 12


def validate_observation_id(obs_id: str) -> tuple[bool, str]:
    """
    Validate an observation_id is production-quality.

    Production IDs are 16-char lowercase hex strings generated by
    sha256(symbol_timestamp)[:16]. This validator rejects:
      - Empty/missing IDs
      - IDs shorter than 12 characters (test artifacts like "no_boto", "abc")
      - IDs starting with forbidden prefixes (test_, mock_, fake_, etc.)
      - IDs containing only digits (likely raw timestamps)

    Returns (valid, reason).
    """
    if not obs_id:
        return False, "observation_id is empty"
    if len(obs_id) < _MIN_OBSERVATION_ID_LENGTH:
        return False, f"observation_id '{obs_id}' too short ({len(obs_id)} < {_MIN_OBSERVATION_ID_LENGTH})"
    obs_upper = obs_id.upper()
    for prefix in FORBIDDEN_PREFIXES:
        if obs_upper.startswith(prefix):
            return False, f"observation_id '{obs_id}' has forbidden prefix '{prefix}'"
    if obs_id.isdigit():
        return False, f"observation_id '{obs_id}' is purely numeric (likely raw timestamp)"
    return True, "valid"


# ═══════════════════════════════════════════════════════════════
# PRODUCTION WRITE GUARD
# ═══════════════════════════════════════════════════════════════


def _is_test_environment() -> bool:
    """
    Detect if running under a test/dev environment.

    Returns True if ANY of these are true:
      - PYTEST_CURRENT_TEST env var exists (set by pytest automatically)
      - 'pytest' or '_pytest' is in sys.modules (pytest is imported)
      - TEST_MODE config flag is True
      - ENVIRONMENT config is "TEST" or "DEV"
    """
    import os
    import sys

    # Env var set by pytest for every test
    if os.environ.get("PYTEST_CURRENT_TEST"):
        return True

    # pytest loaded in process
    if "pytest" in sys.modules or "_pytest" in sys.modules:
        return True

    # Explicit config flags
    try:
        from core import config
        if getattr(config, "TEST_MODE", False):
            return True
        env = getattr(config, "ENVIRONMENT", "PRODUCTION").upper()
        if env in ("TEST", "DEV", "DEVELOPMENT", "STAGING"):
            return True
    except ImportError:
        pass

    return False


def _production_write_guard() -> tuple[bool, str]:
    """
    Runtime gate: blocks ALL S3 writes unless production conditions are met.

    Requires ALL of:
      1. NOT running under test environment
      2. ENGINE_MODE == "V10"
      3. LIVE_MODE == True
      4. ALLOW_PRODUCTION_S3_WRITE == True

    This guard lives inside s3_writer.py so that even direct callers
    (scripts, notebooks, smoke tests) are blocked.

    Returns (allowed, reason).
    """
    # Hard stop: test environment can NEVER write to production bucket
    if _is_test_environment():
        return False, "test_environment_detected"

    try:
        from core import config
    except ImportError:
        return False, "config module unavailable"

    engine_mode = getattr(config, "ENGINE_MODE", "LEGACY")
    live_mode = getattr(config, "LIVE_MODE", False)
    allow_write = getattr(config, "ALLOW_PRODUCTION_S3_WRITE", False)

    if engine_mode != "V10":
        return False, f"ENGINE_MODE={engine_mode} (requires V10)"
    if not live_mode:
        return False, "LIVE_MODE=False (not live trading runtime)"
    if not allow_write:
        return False, "ALLOW_PRODUCTION_S3_WRITE=False (production writes disabled)"

    return True, "V10_LIVE"


# ═══════════════════════════════════════════════════════════════
# PUBLIC API
# ═══════════════════════════════════════════════════════════════


def upload_decision(record: dict[str, Any]) -> bool:
    """
    Upload a V10 decision record to S3.

    Validates schema and symbol before upload.
    Returns True if uploaded, False if rejected or failed.
    """
    obs_id = record.get("observation_id", "?")

    allowed, reason = _production_write_guard()
    if not allowed:
        logger.info("[S3 GUARD] obs_id=%s action=BLOCKED reason=%s", obs_id, reason)
        return False

    if not _validate_for_upload(record, "decision"):
        logger.info("[S3 GUARD] obs_id=%s action=BLOCKED reason=validation_failed", obs_id)
        return False

    logger.info("[S3 GUARD] obs_id=%s action=ALLOWED mode=%s", obs_id, reason)
    symbol = _normalize_symbol(record.get("symbol", ""))
    date_str = _extract_date(record.get("timestamp_utc", 0))
    key = f"v10/decisions/symbol={symbol}/date={date_str}/decisions.jsonl"
    return _append_to_s3(key, record)


def upload_execution(record: dict[str, Any]) -> bool:
    """Upload an execution attempt record to S3."""
    allowed, reason = _production_write_guard()
    if not allowed:
        logger.debug("[S3 GUARD] bucket=%s action=BLOCKED reason=%s", BUCKET_NAME, reason)
        return False
    if not _validate_for_upload(record, "execution"):
        return False
    logger.debug("[S3 GUARD] bucket=%s action=ALLOWED mode=%s", BUCKET_NAME, reason)
    symbol = _normalize_symbol(record.get("symbol", ""))
    date_str = _extract_date(record.get("timestamp_utc", 0))
    key = f"v10/executions/symbol={symbol}/date={date_str}/executions.jsonl"
    return _append_to_s3(key, record)


def upload_outcome(record: dict[str, Any]) -> bool:
    """Upload a trade outcome record to S3."""
    allowed, reason = _production_write_guard()
    if not allowed:
        logger.debug("[S3 GUARD] bucket=%s action=BLOCKED reason=%s", BUCKET_NAME, reason)
        return False
    if not _validate_for_upload(record, "outcome"):
        return False
    logger.debug("[S3 GUARD] bucket=%s action=ALLOWED mode=%s", BUCKET_NAME, reason)
    symbol = _normalize_symbol(record.get("symbol", ""))
    date_str = _extract_date(record.get("timestamp_utc", record.get("exit_time", 0)))
    key = f"v10/outcomes/symbol={symbol}/date={date_str}/outcomes.jsonl"
    return _append_to_s3(key, record)


def upload_events(events: list[dict[str, Any]], observation_id: str = "") -> bool:
    """
    Upload V10 pipeline events (full reasoning timeline) to S3.

    All events for one pipeline evaluation are written as one JSONL batch.
    Schema: v10_event_v1
    """
    if not events:
        return False

    # Production write guard
    allowed, reason = _production_write_guard()
    if not allowed:
        logger.debug("[S3 GUARD] bucket=%s action=BLOCKED dataset=events reason=%s", BUCKET_NAME, reason)
        return False

    # Validate first event for symbol/timestamp
    first = events[0]
    symbol = first.get("symbol", "")
    if not _is_valid_symbol(symbol):
        logger.debug("[V10_S3] events rejected: invalid symbol '%s'", symbol)
        return False

    # Validate all events
    for event in events:
        if not _validate_event(event):
            return False

    symbol = _normalize_symbol(symbol)
    date_str = _extract_date(first.get("timestamp_utc", 0))
    obs_id = observation_id or first.get("observation_id", "unknown")
    key = f"v10/events/symbol={symbol}/date={date_str}/events_{obs_id}.jsonl"

    # Write all events as one JSONL batch
    try:
        import boto3
        client = boto3.client("s3", region_name=BUCKET_REGION)
        lines = "".join(json.dumps(e, default=str) + "\n" for e in events)
        client.put_object(
            Bucket=BUCKET_NAME,
            Key=key,
            Body=lines.encode("utf-8"),
            ContentType="application/jsonl",
        )
        logger.info("[V10_S3] events uploaded: %s (%d events)", key, len(events))
        return True
    except ImportError:
        logger.debug("[V10_S3] boto3 not available — event upload skipped")
        return False
    except Exception as exc:
        logger.warning("[V10_S3] event upload failed: %s", exc)
        return False


# ═══════════════════════════════════════════════════════════════
# VALIDATION
# ═══════════════════════════════════════════════════════════════


def _validate_for_upload(record: dict, dataset: str) -> bool:
    """Validate record before S3 upload."""
    # Symbol check
    symbol = record.get("symbol", "")
    if not _is_valid_symbol(symbol):
        logger.debug("[V10_S3] rejected: invalid symbol '%s'", symbol)
        return False

    # Timestamp range check — reject stale/default/future timestamps
    from core.v10.pipeline_events import validate_timestamp
    ts = record.get("timestamp_utc", 0)
    ts_valid, ts_reason = validate_timestamp(ts)
    if not ts_valid:
        logger.debug("[V10_S3] rejected: %s", ts_reason)
        return False

    # Observation ID validation — central validator
    obs_id = record.get("observation_id", "")
    obs_valid, obs_reason = validate_observation_id(obs_id)
    if not obs_valid:
        logger.debug("[V10_S3] rejected: %s", obs_reason)
        return False

    # Schema validation (decisions only — executions/outcomes have lighter schemas)
    if dataset == "decision":
        valid, violations = validate_decision_record(record)
        if not valid:
            logger.debug("[V10_S3] schema violation: %s", violations[:3])
            return False

    return True


EVENT_SCHEMA_VERSION = "v10_event_v1"

_VALID_EVENT_TYPES = frozenset({
    "V10_MARKET_STATE_COMPLETE",
    "V10_OPPORTUNITY_COMPLETE",
    "V10_STRATEGY_COMPLETE",
    "V10_HORIZON_COMPLETE",
    "V10_ENTRY_COMPLETE",
    "V10_RISK_COMPLETE",
    "V10_EXECUTION_COMPLETE",
    "V10_DECISION_COMPLETE",
})


def _validate_event(event: dict) -> bool:
    """Validate a single V10 event before S3 upload."""
    from core.v10.pipeline_events import validate_timestamp

    # Required fields
    if not event.get("observation_id"):
        return False
    if not event.get("symbol"):
        return False
    if not event.get("event_type"):
        return False

    # Observation ID validation
    obs_valid, _ = validate_observation_id(event.get("observation_id", ""))
    if not obs_valid:
        return False

    # Timestamp validity
    ts = event.get("timestamp_utc", 0)
    valid, _ = validate_timestamp(ts)
    if not valid:
        return False

    # Engine version
    if event.get("engine_version") != "V10":
        return False

    # Event type must be recognised
    if event.get("event_type") not in _VALID_EVENT_TYPES:
        return False

    return True


def _is_valid_symbol(symbol: str) -> bool:
    """Check if symbol is a real trading instrument (not test/mock)."""
    if not symbol:
        return False
    s = symbol.upper()
    # Forbidden prefixes
    for prefix in FORBIDDEN_PREFIXES:
        if s.startswith(prefix):
            return False
    # Must be in allowed set (or canonical form of allowed)
    canonical = s.rstrip("_SB").rstrip(".C").rstrip("_CFD")
    return s in ALLOWED_SYMBOLS or canonical in ALLOWED_SYMBOLS


def _normalize_symbol(symbol: str) -> str:
    """Normalize to canonical form for S3 key."""
    s = symbol.upper()
    for suffix in ("_SB", ".C", "_CFD"):
        if s.endswith(suffix):
            s = s[:-len(suffix)]
    return s


def _extract_date(timestamp: float) -> str:
    """Extract YYYY-MM-DD from unix timestamp."""
    if timestamp > 0:
        dt = datetime.fromtimestamp(timestamp, tz=timezone.utc)
    else:
        dt = datetime.now(timezone.utc)
    return dt.strftime("%Y-%m-%d")


# ═══════════════════════════════════════════════════════════════
# S3 TRANSPORT
# ═══════════════════════════════════════════════════════════════


def _append_to_s3(key: str, record: dict) -> bool:
    """Append a JSONL record to S3. Never raises."""
    obs_id = record.get("observation_id", record.get("decision_id", "unknown"))
    try:
        import boto3
        client = boto3.client("s3", region_name=BUCKET_REGION)
        line = json.dumps(record, default=str) + "\n"

        # S3 doesn't support append — use a unique key per record
        unique_key = key.replace(".jsonl", f"_{obs_id}.jsonl")

        logger.info("[V10_S3] step=put_object obs_id=%s key=%s", obs_id, unique_key)
        client.put_object(
            Bucket=BUCKET_NAME,
            Key=unique_key,
            Body=line.encode("utf-8"),
            ContentType="application/jsonl",
        )
        logger.info("[V10_S3] step=uploaded obs_id=%s key=%s", obs_id, unique_key)
        return True

    except ImportError:
        logger.info("[V10_S3] step=skipped obs_id=%s reason=boto3_unavailable", obs_id)
        return False
    except Exception as exc:
        logger.warning("[V10_S3] step=failed obs_id=%s error=%s", obs_id, exc)
        return False
