"""
Canonical Clock — Single time source for the entire trading system.

RULE: All event timestamps in the system MUST be generated by this module.
      No module may call time.time(), datetime.now(), or any other clock directly
      for event stamping purposes.

Standard: UTC milliseconds (int)
    UTC_MILLI_TIMESTAMP = int(time.time() * 1000)

Properties:
    - Globally sortable (integer comparison)
    - Millisecond precision (sufficient for M5 system)
    - UTC only (no timezone ambiguity)
    - Monotonic-safe (detects backward jumps)
    - Deterministic in replay mode (injectable clock)

Usage:
    from core.clock import utc_ms, utc_ms_to_iso, candle_ts_to_ms

    ts = utc_ms()                           # Current time in UTC millis
    iso = utc_ms_to_iso(ts)                 # "2026-06-27T09:30:15.123Z"
    candle_ms = candle_ts_to_ms(1719388800) # Convert MT5 candle seconds → millis
"""

from __future__ import annotations

import time as _time
from datetime import datetime, timezone

# ─── MODULE STATE ─────────────────────────────────────────────────────────────

_last_ts: int = 0  # Monotonic guard — never emits a timestamp < previous
_clock_override: int | None = None  # For deterministic replay injection


# ─── PRIMARY API ──────────────────────────────────────────────────────────────

def utc_ms() -> int:
    """
    Generate current UTC timestamp in milliseconds.

    This is THE canonical clock for the entire system.
    All events, decisions, entities, and trades must use this.

    Guarantees:
        - Always UTC
        - Always millisecond precision
        - Monotonically non-decreasing (guards against clock skew)
        - Injectable for deterministic replay
    """
    global _last_ts

    if _clock_override is not None:
        ts = _clock_override
    else:
        ts = int(_time.time() * 1000)

    # Monotonic guard: never go backwards
    if ts <= _last_ts:
        ts = _last_ts + 1

    _last_ts = ts
    return ts


def utc_ms_to_iso(ms: int) -> str:
    """
    Convert UTC milliseconds to ISO 8601 string.

    Args:
        ms: UTC milliseconds timestamp

    Returns:
        "2026-06-27T09:30:15.123Z"
    """
    seconds = ms / 1000.0
    dt = datetime.fromtimestamp(seconds, tz=timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.") + f"{ms % 1000:03d}Z"


def utc_ms_to_date(ms: int) -> str:
    """
    Convert UTC milliseconds to date string.

    Args:
        ms: UTC milliseconds timestamp

    Returns:
        "2026-06-27"
    """
    seconds = ms / 1000.0
    dt = datetime.fromtimestamp(seconds, tz=timezone.utc)
    return dt.strftime("%Y-%m-%d")


def candle_ts_to_ms(candle_time: int | float) -> int:
    """
    Convert MT5 candle timestamp (unix seconds) to UTC milliseconds.

    MT5 candle.time is already UTC seconds. This just scales to millis.

    Args:
        candle_time: Unix seconds from MT5 candle

    Returns:
        UTC milliseconds (int)
    """
    return int(float(candle_time) * 1000)


def utc_ms_from_unix(unix_seconds: float) -> int:
    """
    Convert any unix timestamp (seconds, float) to UTC milliseconds.

    Args:
        unix_seconds: Standard unix time (float or int)

    Returns:
        UTC milliseconds (int)
    """
    return int(float(unix_seconds) * 1000)


# ─── REPLAY SUPPORT ──────────────────────────────────────────────────────────

def set_clock_override(ms: int | None) -> None:
    """
    Inject a fixed clock value for deterministic replay.

    Args:
        ms: Fixed UTC milliseconds to return, or None to restore live clock.
    """
    global _clock_override
    _clock_override = ms


def advance_clock(delta_ms: int) -> None:
    """
    Advance the injected clock by delta milliseconds (replay stepping).

    Only works when clock override is active. No-op in live mode.
    """
    global _clock_override
    if _clock_override is not None:
        _clock_override += delta_ms


# ─── FORMATTING HELPERS (backward compat with existing log consumers) ─────────

def utc_ms_to_unix(ms: int) -> float:
    """Convert UTC millis back to unix seconds (float)."""
    return ms / 1000.0


def now_iso() -> str:
    """Shortcut: current time as ISO string. Equivalent to utc_ms_to_iso(utc_ms())."""
    return utc_ms_to_iso(utc_ms())


def now_date() -> str:
    """Shortcut: current date as YYYY-MM-DD string."""
    return utc_ms_to_date(utc_ms())
